/* eslint-disable */
// @generated by `cargo run --manifest-path src-tauri/Cargo.toml --bin generate_ts_types --features typegen`
// This file has been generated by Specta. DO NOT EDIT.

export type WindowMode = "mini" | "input" | "result";

export type ScreenCaptureResult = {
  text: string;
  confidence: number | null;
  timestamp: number;
  window_name: string | null;
};

export type VlmAnalysisResult = {
  content: string;
  timestamp: number;
};

export type WindowInfo = {
  title: string;
  app_name: string;
  pid: number;
  is_focused: boolean;
  z_index: number;
  is_minimized: boolean;
};

